---

- name: build Open Stack inventory
  hosts: jumpbox
  pre_tasks:
    - name: pause
      pause:
        minutes: 1

  roles:
    - role: osp-facter
      when: ansible_product_name ==  'OpenStack Compute'
      tags: [ inventory ]

- name: build AWS inventory
  hosts: localhost
  connection: local
  gather_facts: no

  roles:
    - role: aws-facter
      aws_facter__inventory:
        - group: 'appdbs:children'
          hosts:
            - tag_AnsibleGroup_appdbs
        - group: 'apps:children'
          hosts:
            - tag_AnsibleGroup_apps
        - group: 'frontends:children'
          hosts:
            - tag_AnsibleGroup_frontends
      when: ansible_product_name ==  'AWS EC2 Compute'
      tags: [ inventory ]

- name: install HA proxy
  hosts: frontends
  gather_facts: true
  become: true

  roles:
    - role: conf-repos
      tags: [ system ]
    - role: conf-base
      tags: [ system ]
    - role: svcs-haproxy
      tags: [ haproxy ]

- name: setup app tier
  hosts: apps
  gather_facts: true
  become: true

  roles:
    - role: conf-repos
      tags: [ system ]
    - role: conf-base
      tags: [ system ]
    - role: app-tomcat
      tags: [ app ]

- name: setup database tier
  hosts: appdbs
  gather_facts: true
  become: true

  roles:
    - role: conf-repos
      tags: [ system ]
    - role: conf-base
      tags: [ system ]
    - role: geerlingguy.postgresql
      tags: [ db ]

