---
# tasks file for roles/app-tomcat

- block:
  - name: install tomcat
    yum:
      name: tomcat
      state: latest
    notify: enable_and_restart_tomcat

  - name: create tomcat default web directory
    file:
      path: "{{ app_tomcat__web_root }}"
      state: directory

  - name: copy static index.html to tomcat webroot
    template:
      src: index.html
      dest: "{{ app_tomcat__web_root }}/index.html"
      mode: 0644
    notify: enable_and_restart_tomcat
  when: app_tomcat__state | d('') == 'present'

- block:
  - name: delete tomcat
    yum:
      name: tomcat
      state: absent

  - name: delete tomcat default web directory
    file:
      path: "{{ app_tomcat__web_root }}"
      state: absent

  when: app_tomcat__state | d('') == 'absent'

