---
# tasks file for roles/aws-facter

- name: show instance info
  debug:
    var: hostvars

- name: add host to inventory
  add_host:
    name: "{{ item.inventory_hostname }}"
    group: "{{ item.ec2_tag_AnsibleGroup }}"
  with_dict: "{{ hostvars }}"
  loop_control:
    label: "{{ item.inventory_hostname | d('') + ' ' + item.ec2_tag_AnsibleGroup | d('') }}"
  when: item.ec2_tag_AnsibleGroup | d('') and item.inventory_hostname | d('')

