---
# tasks file for roles/aws-facter

- name: show instance info
  debug:
    var: hostvars

- name: add host to inventory
  add_host:
    name: "{{ item.key }}"
    group: "{{ item.value.ec2_tag_AnsibleGroup }}"
  with_dict: "{{ hostvars }}"
  loop_control:
    label: "{{ item.key | d('') + ' ' + item.value.ec2_tag_AnsibleGroup | d('') }}"

